### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by danielcristho** [danielcristho/danielcristho.site#4]
- [x] Add Giscus component
- [x] Add truncate component
- [x] Add comment component
